#!/usr/bin/env bash
set -e

BLACK_ARG="--check"
RUFF_ARG=""

if [ "$1" = "fix" ] ; then
    BLACK_ARG=""
    RUFF_ARG="--fix"
fi

echo "run black"
black pyslink.py ${BLACK_ARG}
echo "run ruff"
ruff pyslink.py ${RUFF_ARG}
echo "run mypy"
mypy pyslink.py
